version: '2'
services:
    instaplatform-app:
        image: instaplatform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://instaplatform-postgresql:5432/instaplatform
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    instaplatform-postgresql:
        extends:
            file: postgresql.yml
            service: instaplatform-postgresql
